version: 2.0
jobs:
  build:
   #working_directory: /root
    docker:
      - image: ubuntu:18.04
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circleci_test
    steps:
      - checkout
      - run: 
          name: install wget
          command: apt-get update && apt-get install -y wget
      - run:
          name: install dockerize
          command: apt-get update && https://github.com/jwilder/dockerize/releases/download/0.3.0/dockerize-linux-amd64-0.3.0.tar.gz
       #   environment:
       #    DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
